version: '3.9'
services:
  postgresql:
    image: postgres:14.1-alpine
    container_name: vkdb
    environment:
      - POSTGRES_DB=vk
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    networks:
      - backend



  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/vk
      - --username=username
      - --password=password
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  pgdata:
networks:
  backend: